FROM docker.io/rust:alpine as base
RUN apk add --no-cache gcc musl-dev g++ git pkgconfig curl
WORKDIR /usr/rain
ENV CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
ENV SQLX_OFFLINE=true

FROM base AS build
COPY . .
RUN cargo build --release -p rain-ci-migrator --locked --target x86_64-unknown-linux-musl

FROM base AS rain
WORKDIR /usr/rain
COPY --from=build /usr/rain/target/x86_64-unknown-linux-musl/release/rain-ci-migrator /usr/local/cargo/bin/rain-ci-migrator
COPY ./ci/migrations migrations
ENV MIGRATIONS_DIR=migrations
ENTRYPOINT ["rain-ci-migrator"]
