FROM docker.io/rust:alpine as base
RUN apk add --no-cache gcc musl-dev g++ git pkgconfig curl openssl-dev
WORKDIR /usr/rain
ENV CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
ENV SQLX_OFFLINE=true

FROM base AS build
COPY . .
RUN cargo build --release -p rain-ci-web --locked --target x86_64-unknown-linux-musl

FROM base AS rain
WORKDIR /usr/rain
COPY --from=build /usr/rain/target/x86_64-unknown-linux-musl/release/rain-ci-web /usr/local/cargo/bin/rain-ci-web
ENV RUST_LOG=info
ENTRYPOINT ["rain-ci-web"]
