build:
    tree-sitter generate --abi 14
    tree-sitter build --wasm

playground: build
    tree-sitter playground
    
install-helix: build
    mkdir -p ~/.config/helix/runtime/queries/rain/
    cp ./queries/highlights.scm ~/.config/helix/runtime/queries/rain/highlights.scm
    hx --grammar build

test: build
    tree-sitter parse --quiet ../*.rain
