ALTER TABLE repos ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE repos_id_seq;
ALTER TABLE repos ALTER COLUMN id SET DATA TYPE BIGINT;
ALTER TABLE repos ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
SELECT setval(pg_get_serial_sequence('repos', 'id'), COALESCE(MAX(id), 1)) FROM repos;

ALTER TABLE repo_hosts ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE repo_hosts_id_seq;
ALTER TABLE repo_hosts ALTER COLUMN id SET DATA TYPE BIGINT;
ALTER TABLE repo_hosts ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
SELECT setval(pg_get_serial_sequence('repo_hosts', 'id'), COALESCE(MAX(id), 1)) FROM repo_hosts;

ALTER TABLE runs ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE runs_id_seq;
ALTER TABLE runs ALTER COLUMN id SET DATA TYPE BIGINT;
ALTER TABLE runs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
SELECT setval(pg_get_serial_sequence('runs', 'id'), COALESCE(MAX(id), 1)) FROM runs;

ALTER TABLE finished_runs ALTER COLUMN run DROP DEFAULT;
DROP SEQUENCE finished_runs_run_seq;
ALTER TABLE finished_runs ALTER COLUMN run SET DATA TYPE BIGINT;

ALTER TABLE migrations ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE migrations_id_seq;
