[package]
name = "rain-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
base16.workspace = true
chrono.workspace = true
ciborium.workspace = true
dirs = "6.0"
flate2 = "1.1"
git2 = "0.20"
ignore = "0.4"
indexmap.workspace = true
libc.workspace = true
liblzma = "0.4"
log.workspace = true
lru = "0.16"
num-bigint = "0.4"
poison_panic.path = "../poison_panic"
rain-lang.path = "../lang"
serde.workspace = true
sha2.workspace = true
tar = "0.4"
thiserror.workspace = true
toml.workspace = true
ureq.workspace = true
uuid.workspace = true
zip = { version = "8.0", features = ["deflate"], default-features = false }
zstd = "0.13"
alias.path = "../alias"

[dev-dependencies]
insta.workspace = true
tempfile.workspace = true
test-log.workspace = true
