FROM alpine AS blender-install

FROM docker.io/rust:1.97-slim
WORKDIR /usr/rain
RUN rustup component add rustfmt clippy
RUN \
  apt-get -qqy update && \
  apt-get -qqy install libgit2-dev pkg-config libssl-dev curl xz-utils libasound2-dev clang nodejs python3-numpy libxxf86vm1 libxfixes3 libxi6 libx11-6 libxkbcommon0 libgl1 libxrender1 libsm6 && \
  apt-get remove -y --auto-remove

ADD \
  --checksum=sha256:{{SHA256}} \
  --chmod=550 \
  https://storage.googleapis.com/rain-e870e063/releases/{{VERSION}}/rain-ci-coordinator \
  /bin/rain-ci-coordinator

ENV RUST_LOG=info
ENTRYPOINT ["rain-ci-coordinator"]
