FROM docker.io/rust:slim as base

RUN apt-get -qqy update && apt-get -qqy install pkg-config libssl-dev

WORKDIR /usr/rain

ENV \
    CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse \
    CARGO_BUILD_TARGET_DIR=/target

FROM base as build
# Actually build things
COPY . .
# Build the rain-ci server
RUN cargo install --path ci/coordinator --locked

FROM base as rain

COPY --from=build /usr/local/cargo/bin/rain-ci-coordinator /usr/local/cargo/bin/rain-ci-coordinator
ENV RUST_LOG=info
ENTRYPOINT ["rain-ci-coordinator"]
