FROM docker.io/rust:slim as base
RUN rustup component add rustfmt clippy
RUN apt-get -qqy update && apt-get -qqy install pkg-config libssl-dev curl xz-utils libasound2-dev

WORKDIR /usr/rain

ENV CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse

FROM base as build
# Actually build things
COPY . .
# Build the rain-ci server
RUN cargo install --path ci/coordinator --locked

FROM base AS blender-install
ARG BLENDER_VERSION=4.5.1
ARG BLENDER_SHORT_VERSION=4.5
RUN curl -O https://mirrors.ocf.berkeley.edu/blender/release/Blender$BLENDER_SHORT_VERSION/blender-$BLENDER_VERSION-linux-x64.tar.xz
RUN echo "085a7ed4ed80c3cb66783bad76f236f39897de5d33884abd133e0c6db94c0f14  blender-$BLENDER_VERSION-linux-x64.tar.xz" | sha256sum -c
RUN tar -xf blender-$BLENDER_VERSION-linux-x64.tar.xz -C /
RUN mv /blender-$BLENDER_VERSION-linux-x64 /blender

FROM base as rain

# Install blender
RUN apt-get -qqy install python3-numpy libxxf86vm1 libxfixes3 libxi6 libx11-6 libxkbcommon0 libgl1 libxrender1 libsm6 && apt-get remove -y --auto-remove
COPY --from=blender-install /blender /blender
ENV PATH="${PATH}:/blender"

COPY --from=build /usr/local/cargo/bin/rain-ci-coordinator /usr/local/cargo/bin/rain-ci-coordinator
ENV RUST_LOG=info
ENTRYPOINT ["rain-ci-coordinator"]
